Add index offset
woylie/flop_phoenix pull request #140
Opened 2022-11-12 17:04 UTC by andreasknoepfle

**Description**

I introduced an index parameter to fix #139 
Works for me like a charm :) 

**Checklist**

- [ ] I added tests that cover my proposed changes.
- [ ] I updated the documentation related to my changes (if applicable).

2022-11-12 23:49 UTC, woylie requested changes
Thank you, looks good to me! Can you rename the `index` attribute to `offset`? I think that better describes what this is for.

2022-11-14 07:23 UTC, andreasknoepfle commented
Renamed and improved the docs a little more.

2022-11-14 10:02 UTC, woylie approved these changes

2022-11-14 10:02 UTC, woylie commented
Thank you!

2022-11-14 10:16 UTC, merged